import urllib.request
import xml.etree.ElementTree as ET

from pprint import pprint as pp

def main():
    cachedList = ['Monterey Bay Alternative Medicine',
                'Valley Pure',
                'Elemental Wellness Center',
                'White Fire',
                "Buddy's Cannabis",
                'Harborside',
                'Caliva',
                'Airfield Supply Co.',
                'Purple Lotus Patient Center',
                'KindPeoples 1',
                'KindPeoples 2',
                'Santa Cruz Veterans Alliance',
                'CannaCruz',
                'Capitola Healing Association Inc.',
                'Point Loma Patients Consumer Cooperative',
                'Urbn Leaf Dispensary 1',
                'Urbn Leaf Dispensary 2',
                'Harbor Collective',
                'Mankind Cooperative',
                'The Healing Center San Diego',
                'A Green Alternative MMCC',
                'Torrey Holistics',
                '530 Cannabis',
                'Queen of Dragons',
                'Berkeley Patients Group',
                'Phytologie Oakland',
                'Purple Heart Patient Center',
                'Green Pearl Organics',
                'West Coast Cannabis Club',
                "Mother Earth's Farmacy",
                'Cathedral City Care Collective North',
                'P&S Ventures',
                "Desert's Finest Patient's Collective",
                'Desert Organic Solutions',
                'Green Cross Pharma',
                'HOTN Cultivation Co.',
                'Ecological Cannabis Organization',
                'Revolution Emporium',
                'Kure Wellness',
                'Elevate Shasta Wellness',
                'Mount Shasta Patients Collective',
                'MMOF San Diego Retail',
                'Harborside',
                'Solful',
                'Omega Group',
                'Therapeutic Healthcare Collective',
                'Santa Cruz Naturals',
                'Canna Culture Collective',
                'Creekside Wellness',
                'Emerald Pharms',
                'Apothekare',
                'Natural Herbal Pain Relief',
                'CA Systematize',
                'Metro Health Systems ',
                'Mercy Wellness',
                'A Therapeutic Alternative',
                'ShowGrow',
                'Central Coast Wellness Center',
                'TFA Inc.',
                'Love In It Cooperative',
                "People's OC",
                '420 Central',
                'OC3',
                'Cannabis Buyers Club of Berkeley',
                'East of Eden Cannabis Co.',
                'Blum',
                'Leave it to Nature',
                'All About Wellness',
                'Redwood Coast Lifestyles ',
                'MedMen OC',
                'From the Earth',
                'Holistic Healing Collective',
                'Cathedral City Releaf',
                'Northstar Holistic Collective',
                'Higher Level of Care',
                'SPARC',
                'Green Remedy',
                'The Green Heart Collective',
                'Theraleaf Relief',
                'California Naturopathic Agricultural Association #7',
                'Migliore',
                'BSCB Enterprises',
                'The Joint',
                'Palm Springs Safe Access',
                'Strain Station',
                'Hand N Hand Patient Care',
                'Curbstone Exchange',
                'Garden of Eden',
                'River City Phoenix',
                'Sacramento Community Cannabis Collective',
                'Valley Health Options Collective',
                'Golden Health & Wellness',
                'Alternative Medical Center',
                'Horizon Nonprofit Collective',
                'South Coast Safe Access',
                '10 Spot Collective',
                'Super Clinik Yale',
                'Bud and Bloom',
                'Pacafi Cooperative',
                'Atomic Budz',
                'The Humboldt County Collective',
                'Zen Healing',
                'Los Angeles Patients & Caregivers Group',
                'Alternative Herbal Health Services',
                'MedMen WeHo',
                'East Bay Therapeutics',
                'Emerald Skyway',
                'Evergreen',
                'The Genezen Project',
                'Southwest Patient Group',
                'New Generation',
                'Super Clinik',
                'Patients Care Collective',
                'We Are Hemp',
                'Balboa Avenue Cooperative',
                'Triple C Collective',
                'NRC Holistic Health Services Clinic',
                'Brown Dog Health and Wellness',
                'Blum Oak',
                'Artifact Nursery',
                'Florin Wellness Center',
                'Medithrive Mission',
                'Grass Roots',
                'Harvest on Geary',
                'The Apothecarium - Castro',
                'ReLeaf Herbal Cooperative',
                'The Green Cross',
                'San Diego Recreational Cannabis (SDRC)',
                'Higher Level of Care Seaside',
                'Cloud 9 Alliance',
                'Shambhala Medical Cannabis Collective',
                'Hugs Alternative Care',
                'CC101',
                '7 Stars Holistic Healing Center',
                'The Apothecarium - SOMA',
                'THC',
                'Safe Accessible Solutions',
                'PSA Organica',
                'Lakeside Herbal Solutions']

    #url = 'http://www.google.com/maps/d/kml?forcekml=1&mid=1f4p3zPa1uU_gRnbQzMAqCZTPzD4' # National Parks
    # url = 'http://www.google.com/maps/d/kml?forcekml=1&mid=1Zn_fIUf06TLnOshLtZCqdbbHLCo' # CA Parks
    url = 'http://www.google.com/maps/d/kml?forcekml=1&mid=1aJKR8O-8BWOb9uR7p_2UmapNTL6n154B' # 420
   
    with urllib.request.urlopen(url) as response:
        html = response.read()
        root = ET.fromstring(html)
    
    listOfPlacemarks = []
    for i in root[0][-1].findall('{http://www.opengis.net/kml/2.2}Placemark'):
        myText = i[0].text.replace('\xa0', '')
        myText = myText.replace('\n', '')
        listOfPlacemarks.append(myText)

    for i in listOfPlacemarks:
        if i not in cachedList:
            print(i)

    print('done')

    # pp(listOfPlacemarks)

if __name__ == '__main__':
    main()